language: php

php:
  - 5.4

before_script:
  - wget http://pecl.php.net/get/mongo-1.2.12.tgz
  - tar -xzf mongo-1.2.12.tgz
  - sh -c "cd mongo-1.2.12 && phpize && ./configure --enable-mongo && make && sudo make install"
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - git submodule update --init
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - rm .gitmodules
  - git rm --cached vendor/ZF2
  - cp ../doctrineExtensionsModule/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - rm -rf vendor/superdweebie/doctrine-extensions-module
  - cp -r ../doctrineExtensionsModule vendor/superdweebie/
  - mv vendor/superdweebie/doctrineExtensionsModule vendor/superdweebie/doctrine-extensions-module
  - mkdir public/js/dojo_src
  - rm config/application.config.php
  - cp ../doctrineExtensionsModule/tests/test.application.config.php config/
  - mv config/test.application.config.php config/application.config.php

script:
  - ./vendor/bin/doctrine-module odm:generate:dojo
  - cd vendor/superdweebie/doctrine-extensions-module
  - phpunit
